name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *" # Executa todos os dias à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: santanna37
          outputs: dist/snake.svg
      - uses: actions/upload-artifact@v3  # Atualizado para v3
        with:
          name: snake
          path: dist
