name: Generate Snake
on:
  schedule:
    - cron: "0 0 * * *" # Executa todos os dias à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar animação Snake
        uses: Platane/snk@v3
        with:
          github_user_name: santanna37
          outputs: |
            dist/snake.svg

      - name: Upload da animação
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist
